services:
  - type: web
    name: empire-mafia-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PORT
        value: 8000
      - key: USE_POLLING
        value: "true"
